### ISSUE TITLE
How to deploy @saas/api on Vercel?

### ISSUE THREAD

**Issue by Cyronlee** [rcrdk/nextjs-fastify-saas-rbac#15]
This project has a very high degree of completion.

Is it possible to deploy @saas/api on Vercel by serverless mode like this?

https://fastify.dev/docs/latest/Guides/Serverless/#vercel

**Comment by rcrdk** [comment]
Hey,
The Vercel deploying of API is not on my roadmap by now, but the project is ready to deploy its API on [Render](https://render.com). You can deploy using GitHub repository and setting an configuration at Render:

- **Root Directory:** apps/api
- **Build Command:** pnpm install --frozen-lockfile; pnpm run build
- **Start Command:** pnpm prisma migrate deploy; pnpm prisma generate; pnpm run start
